server: # webserver port(default : 8080, 0으로 하면 random port)
  port: 8888
#ssl 적용 (keytool 이용해서 인증서 만든 후 application root에 위치)
#ssl 적용시 https 접속(http도 접속 가능하게 하려면 Applition.java 에 추가 Connector 설정)
#server.ssl.key-store=keystore.p12
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-password=123456
#server.ssl.key-alias=spring

#Property예제
kkk: KKKKKKKK
randomvalue: ${random.int} ${kkk} AAAAAAA
bnzprops:
  age: 10
  full-name: bonzo
  name: bnz


#정적리소스
# - 기본 리소스 위치 classpath: /static /public /resources /META-INF/resources
# - (localhost/hello.html  -> localhost/static/hello.html 로 요청해야 함)
#spring.mvc.static-path-pattern=/static/**
# - 이방법 보다는 WebConfig.java 의 addResourceHandlers를 이용하는 걸 추천(기본 정적 리소스path는 유지하면서 추가 설정 가능)

#thymeleaf 사용시 재구동없이 바로 반영
spring:
  thymeleaf:
    cache: false
# h2 - inmemory db http://localhost:8888/h2-console 접속 가능
# SampleRunner 참고(구동시 create db, insert)
  h2:
    console:
      enabled: false

# jdbc사용(mysql, postgresSQL 등. db는 개별 설치)
#-------------------create database springbootdb DEFAULT character set utf8;
#-------------------drop user bonzo@localhost;
#-------------------create user bonzo@localhost IDENTIFIED by 'dhtmdwns1!';
#-------------------create user 'bonzo'@'%' IDENTIFIED by 'dhtmdwns1!';
#-------------------grant all PRIVILEGES on *.* to bonzo@localhost IDENTIFIED by 'dhtmdwns1!' with grant option;
#-------------------flush PRIVILEGES;
#spring.datasource.hikari.maximum-pool-size=4
#spring.datasource.url=jdbc:mysql://localhost:3306/springbootdb
#spring.datasource.username=bonzo
#spring.datasource.password=dhtmdwns1!


#CREATE TABLE "ACCOUNT"
#(	ID       NUMBER(15,0) NOT NULL,
#   USERNAME VARCHAR2(50) NOT NULL,
#   PASSWORD VARCHAR2(200),
#   PRIMARY KEY ("ID"));
#
# CREATE TABLE AU01
# (  LOB_CD    VARCHAR2(50) NOT NULL,
# ITEM_NAME VARCHAR2(50) NOT NULL,
# SEQ_NO     NUMBER(15,0) NOT NULL,
# ITEM_ATTR01 VARCHAR2(50) ,
# ITEM_ATTR02 VARCHAR2(50) ,
# ITEM_ATTR03 VARCHAR2(50) ,
# ITEM_ATTR04 VARCHAR2(50) ,
# ITEM_ATTR05 NUMBER(15,0) ,
# PRIMARY KEY (LOB_CD, ITEM_NAME, SEQ_NO));
#
# CREATE TABLE AU02
# (  LOB_CD    VARCHAR2(50) NOT NULL,
# ITEM_NAME VARCHAR2(50) NOT NULL,
# ITEM_DETL VARCHAR2(50) NOT NULL,
# SEQ_NO     NUMBER(15,0) NOT NULL,
# ITEM_DETL_ATTR01 VARCHAR2(50) ,
# ITEM_DETL_ATTR02 VARCHAR2(50) ,
# ITEM_DETL_ATTR03 VARCHAR2(50) ,
# ITEM_DETL_ATTR04 VARCHAR2(50) ,
# ITEM_DETL_ATTR05 NUMBER(15,0) ,
# PRIMARY KEY (LOB_CD, ITEM_NAME, ITEM_DETL, SEQ_NO));

  # 데이터베이스 연결 정보
  datasource:
    # oracle
    #driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@localhost:1521/XE
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/g2mDB?serverTimezone=Asia/Seoul
    username: g2m
    password: g2m1!g2m2@
    # 커넥션 풀 (HikariCP) 설정 (선택)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  # JPA 설정
  # spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  swagger-ui:
    csrf:
      enabled: true

# MyBatis
mybatis:
  mapper-locations: file:src/main/java/com/bnz/samg/**/*Query.xml # xml파일을 src/main/java 하위에 두고 싶을때...(비추천)
#  mapper-locations: classpath:mapper/*Query.xml # src/main/resources 하위에 놓는경우(default)
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: NULL

telegram:
  bot:
    token: 777630358:AAElntpm3KBBIshGfBMqL_65VYKqbX3Xn-I
    username: bzNotiTestBot
  chat:
    id: -1001163615391

# Apple 앱 푸시
apns:
  team-id: "6N5396RU93" #Apple # Developer 계정 Team ID
  key-id: "M48CNFDVZQ" # AuthKey_XXXX.p8 의 XXXX 부분
  p8-path: "keys/AuthKey_M48CNFDVZQ.p8"
  topic: "com.bnz.StepMon"
  use-sandbox: true  # 개발/디버그: true, TestFlight/배포: false

#로깅(기본 INFO 로깅) ########################################
logging:
  level:
    root: INFO
    org.mybatis: DEBUG # MyBatis SQL 로그
    org.apache.ibatis: DEBUG # MyBatis 내부 SQL 매핑 정보 (선택)
    jdbc.sqlonly: DEBUG
    # Spring Data JPA 관련 로그
    org.springframework.data.jpa: DEBUG
    # Hibernate SQL 로그
    # logging.level.org.hibernate=DEBUG
    org.hibernate.SQL: DEBUG
    # Hibernate 파라미터 바인딩 로그
    org.hibernate.type.descriptor.sql: TRACE
    # Spring Web 요청/응답 정보를 확인하려면:
    org.springframework.web: DEBUG
#logging.file=aaa.log
#logging.path=logdir
    com.bnz: DEBUG #로깅packge단위로